<html>
    <meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl() ?>">
    <body>
        <div class="page-head">
            <h3><?php echo Mage::helper('payfast')->__('Payment was canceled') ?></h3>
        </div>
        <p><?php echo Mage::helper('payfast')->__('Please <a href="%s">continue shopping</a>.', $this->getContinueShoppingUrl()) ?></p>
    </body>
</html>